export const MUTATE_ADD_TODO = 'MUTATE_ADD_TODO';
export const MUTATE_UPDATE_DATE = 'MUTATE_UPDATE_DATE';
export const MUTATE_DELETE_TODO = 'MUTATE_DELETE_TODO';
export const MUTATE_CLEAR_TODOS = 'MUTATE_CLEAR_TODOS';